version: "3.3"
name: avatar-web
services:
  avatar-web:
    container_name: avatar-react-web
    image: avatar-react-web_image
    build: .
    ports:
      - "1000:1000"
    environment:
      NODE_ENV: production
    command: pnpm run preview

