version: "3.3"
name: avatar-web
services:
  web:
    container_name: avatar-react-web_container
    # iamge: online_movie_booking-react-web_iamge  // adding property image is not allow
    build: .
    ports:
      - "1000:1000"
    environment:
      NODE_ENV: production
    command: pnpm run preview

