version: "3.3"
services:
  web:
    container_name: online_movie_booking-react-web_container
    # iamge: online_movie_booking-react-web_iamge  // adding property image is not allow
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: pnpm run preview

